# create an author
POST http://localhost:8080/authors
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "description": "A passionate writer and tech enthusiast."
}

###

# create a category
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Fantasy",
}